
import { type VocabularyWord } from './types';

export const LOCAL_STORAGE_KEY = 'publicGalleryPlannerState_v1_react';

export const VOCABULARY: VocabularyWord[] = [
    { eng: "abandon", kor: "버리다, 포기하다" },
    { eng: "abate", kor: "줄이다, 완화하다" },
    { eng: "abbreviate", kor: "줄여 쓰다, 축약하다" },
    { eng: "abdicate", kor: "퇴위하다, 포기하다" },
    { eng: "abduct", kor: "유괴하다" },
    { eng: "aberrant", kor: "비정상적인, 도리를 벗어난" },
    { eng: "abhor", kor: "몹시 싫어하다, 혐오하다" },
    { eng: "abide by", kor: "준수하다, 지키다" },
    { eng: "abolish", kor: "폐지하다" },
    { eng: "abort", kor: "중단하다, 유산하다" },
    { eng: "abound", kor: "풍부하다" },
    { eng: "abrasive", kor: "연마제, 거친" },
    { eng: "abridge", kor: "요약하다" },
    { eng: "abrogate", kor: "폐지하다, 철폐하다" },
    { eng: "abrupt", kor: "갑작스러운, 퉁명스러운" },
    { eng: "abscond", kor: "도망가다, 자취를 감추다" },
    { eng: "absolve", kor: "용서하다, 무죄를 선언하다" },
    { eng: "abstain", kor: "삼가다, 절제하다" },
    { eng: "abstemious", kor: "절제하는, 금욕적인" },
    { eng: "abstract", kor: "추상적인, 요약" },
    { eng: "abstruse", kor: "난해한, 심오한" },
    { eng: "absurd", kor: "터무니없는, 불합리한" },
    { eng: "abundant", kor: "풍부한" },
    { eng: "abuse", kor: "남용하다, 학대하다" },
    { eng: "abysmal", kor: "최악의, 심연의" },
    { eng: "accede", kor: "동의하다, 취임하다" },
    { eng: "accelerate", kor: "가속하다" },
    { eng: "accessible", kor: "접근하기 쉬운" },
    { eng: "acclaim", kor: "환호하다, 칭송하다" },
    { eng: "accolade", kor: "포상, 칭찬" },
    { eng: "accommodate", kor: "수용하다, 적응시키다" },
    { eng: "accomplice", kor: "공범자" },
    { eng: "accord", kor: "일치하다, 협정" },
    { eng: "accost", kor: "다가가 말을 걸다" },
    { eng: "account for", kor: "설명하다, 차지하다" },
    { eng: "accrete", kor: "증가하다, 부착하다" },
    { eng: "accumulate", kor: "축적하다" },
    { eng: "accuse", kor: "고발하다, 비난하다" },
    { eng: "acerbic", kor: "신랄한, 가혹한" },
    { eng: "acknowledge", kor: "인정하다" },
    { eng: "acme", kor: "절정, 정점" },
    { eng: "acquiesce", kor: "묵인하다, 마지못해 따르다" },
    { eng: "acquire", kor: "얻다, 습득하다" },
    { eng: "acquit", kor: "무죄를 선고하다" },
    { eng: "acrimonious", kor: "신랄한, 통렬한" },
    { eng: "acute", kor: "날카로운, 급성의" },
    { eng: "adamant", kor: "단호한, 견고한" },
    { eng: "adapt", kor: "적응하다, 맞추다" },
    { eng: "address", kor: "연설하다, 다루다" },
    { eng: "adduce", kor: "제출하다, 인용하다" },
    { eng: "adept", kor: "능숙한" },
    { eng: "adequate", kor: "적절한, 충분한" },
    { eng: "adherent", kor: "지지자, 추종자" },
    { eng: "adjacent", kor: "인접한, 가까운" },
    { eng: "adjourn", kor: "휴회하다, 연기하다" },
    { eng: "admonish", kor: "훈계하다, 경고하다" },
    { eng: "adolescent", kor: "청소년기의, 청소년" },
    { eng: "adorn", kor: "장식하다" },
    { eng: "adroit", kor: "솜씨 좋은, 능숙한" },
    { eng: "adulterate", kor: "불순물을 섞다" },
    { eng: "adverse", kor: "불리한, 반대의" },
    { eng: "adversity", kor: "역경, 불행" },
    { eng: "advocate", kor: "옹호하다" },
    { eng: "affable", kor: "상냥한, 붙임성 있는" },
    { eng: "affect", kor: "영향을 미치다, ~인 체하다" },
    { eng: "affiliate", kor: "제휴하다, 가입하다" },
    { eng: "affinity", kor: "친밀감, 관련성" },
    { eng: "affirm", kor: "단언하다, 확언하다" },
    { eng: "afflict", kor: "괴롭히다" },
    { eng: "affluent", kor: "부유한" },
    { eng: "affront", kor: "모욕하다, 모욕" },
    { eng: "aggravate", kor: "악화시키다, 화나게 하다" },
    { eng: "aggregate", kor: "합계, 모으다" },
    { eng: "aggressive", kor: "공격적인, 적극적인" },
    { eng: "agile", kor: "민첩한, 날렵한" },
    { eng: "agitate", kor: "선동하다, 동요시키다" },
    { eng: "alias", kor: "가명" },
    { eng: "alienate", kor: "소외시키다, 멀리하다" },
    { eng: "allay", kor: "가라앉히다, 완화하다" },
    { eng: "allege", kor: "주장하다, 단언하다" },
    { eng: "alleviate", kor: "완화하다" },
    { eng: "allocate", kor: "할당하다, 배분하다" },
    { eng: "allowance", kor: "용돈, 허용량" },
    { eng: "altercation", kor: "언쟁, 논쟁" },
    { eng: "alternative", kor: "대안, 양자택일" },
    { eng: "altruistic", kor: "이타적인" },
    { eng: "amalgamate", kor: "합병하다" },
    { eng: "amass", kor: "모으다, 축적하다" },
    { eng: "ambiguous", kor: "모호한" },
    { eng: "ambivalent", kor: "양면적인, 모순되는" },
    { eng: "amble", kor: "느긋하게 걷다" },
    { eng: "ameliorate", kor: "개선하다" },
    { eng: "amenable", kor: "순종하는, 잘 받아들이는" },
    { eng: "amend", kor: "수정하다, 개정하다" },
    { eng: "amenity", kor: "편의 시설, 쾌적함" },
    { eng: "amiable", kor: "상냥한, 친절한" },
    { eng: "amicable", kor: "우호적인, 평화적인" },
    { eng: "amorphous", kor: "무정형의" },
    { eng: "ample", kor: "충분한, 넓은" },
    { eng: "analogy", kor: "유추, 비슷함" },
    { eng: "anarchy", kor: "무정부 상태, 혼란" },
    { eng: "anecdote", kor: "일화" },
    { eng: "animated", kor: "활기찬, 생생한" },
    { eng: "animosity", kor: "적대감, 증오" },
    { eng: "annihilate", kor: "전멸시키다" },
    { eng: "annual", kor: "매년의, 연간의" },
    { eng: "annul", kor: "무효로 하다, 취소하다" },
    { eng: "anomaly", kor: "변칙, 이례" },
    { eng: "anonymous", kor: "익명의" },
    { eng: "antagonize", kor: "적대감을 불러일으키다" },
    { eng: "anticipate", kor: "예상하다, 기대하다" },
    { eng: "antipathy", kor: "반감, 혐오" },
    { eng: "antiquated", kor: "구식의, 낡은" },
    { eng: "apathy", kor: "무관심" },
    { eng: "apex", kor: "정점, 최고조" },
    { eng: "aplomb", kor: "침착, 평정" },
    { eng: "appall", kor: "오싹하게 하다" },
    { eng: "apparatus", kor: "기구, 장치" },
    { eng: "apparent", kor: "명백한, 외관상의" },
    { eng: "appease", kor: "달래다, 진정시키다" },
    { eng: "appraise", kor: "평가하다, 감정하다" },
    { eng: "appreciable", kor: "상당한, 눈에 띄는" },
    { eng: "apprehend", kor: "체포하다, 이해하다, 걱정하다" },
    { eng: "apprise", kor: "알리다, 통지하다" },
    { eng: "approbation", kor: "승인, 칭찬" },
    { eng: "arbitrary", kor: "임의의, 독단적인" },
    { eng: "arbitrate", kor: "중재하다" },
    { eng: "arcane", kor: "신비로운, 비밀의" },
    { eng: "archaic", kor: "고대의, 낡은" },
    { eng: "arduous", kor: "힘든, 끈기 있는" },
    { eng: "arid", kor: "건조한, 불모의" },
    { eng: "aromatic", kor: "향기로운" },
    { eng: "arrogant", kor: "거만한, 오만한" },
    { eng: "articulate", kor: "분명히 말하다, 명료한" },
    { eng: "artifice", kor: "책략, 교활함" },
    { eng: "ascend", kor: "오르다, 상승하다" },
    { eng: "ascertain", kor: "확인하다, 알아내다" },
    { eng: "aspire", kor: "열망하다, 동경하다" },
    { eng: "assail", kor: "공격하다, 괴롭히다" },
    { eng: "assent", kor: "동의하다, 찬성하다" },
    { eng: "assert", kor: "주장하다, 단언하다" },
    { eng: "assess", kor: "평가하다, 부과하다" },
    { eng: "assiduous", kor: "근면한, 성실한" },
    { eng: "assimilate", kor: "동화시키다, 소화하다" },
    { eng: "assuage", kor: "달래다, 완화하다" },
    { eng: "assume", kor: "가정하다, (책임을) 떠맡다" },
    { eng: "astonish", kor: "놀라게 하다" },
    { eng: "astute", kor: "기민한, 빈틈없는" },
    { eng: "atrocity", kor: "잔학 행위" },
    { eng: "atrophy", kor: "위축, 쇠약" },
    { eng: "attenuate", kor: "약화시키다, 가늘게 하다" },
    { eng: "attest", kor: "증명하다, 입증하다" },
    { eng: "attribute", kor: "~의 탓으로 돌리다, 속성" },
    { eng: "audacious", kor: "대담한, 뻔뻔한" },
    { eng: "augment", kor: "증가시키다, 늘리다" },
    { eng: "auspicious", kor: "길조의, 상서로운" },
    { eng: "austere", kor: "엄격한, 검소한" },
    { eng: "authentic", kor: "진짜의, 신뢰할 만한" },
    { eng: "autocratic", kor: "독재적인" },
    { eng: "autonomous", kor: "자치의, 자율적인" },
    { eng: "avarice", kor: "탐욕" },
    { eng: "avert", kor: "피하다, 막다" },
    { eng: "avid", kor: "열심인, 열렬한" },
    { eng: "awe", kor: "경외, 두려움" },
    { eng: "awkward", kor: "어색한, 서투른" },
    { eng: "banal", kor: "진부한, 평범한" },
    { eng: "banish", kor: "추방하다" },
    { eng: "bargain", kor: "흥정하다, 싸게 산 물건" },
    { eng: "barrister", kor: "법정 변호사" },
    { eng: "beat-up", kor: "낡은, 지친" },
    { eng: "becoming", kor: "어울리는, 적절한" },
    { eng: "beef up", kor: "강화하다, 보강하다" },
    { eng: "bellicose", kor: "호전적인, 싸우기 좋아하는" },
    { eng: "belligerent", kor: "호전적인, 교전중인" },
    { eng: "benediction", kor: "축복, 감사기도" },
    { eng: "beneficial", kor: "유익한, 이로운" },
    { eng: "benevolent", kor: "자비로운, 친절한" },
    { eng: "benign", kor: "상냥한, 양성의" },
    { eng: "bent", kor: "소질, 경향" },
    { eng: "bequeath", kor: "유언으로 남기다" },
    { eng: "berate", kor: "호되게 꾸짖다" },
    { eng: "bereaved", kor: "유족, 사별한" },
    { eng: "beset", kor: "괴롭히다, 포위하다" },
    { eng: "besiege", kor: "포위하다, 둘러싸다" },
    { eng: "bestow", kor: "주다, 수여하다" },
    { eng: "biannual", kor: "연 2회의" },
    { eng: "biennial", kor: "2년마다의" },
    { eng: "bilateral", kor: "양쪽의, 상호적인" },
    { eng: "bigotry", kor: "편협, 고집" },
    { eng: "bizarre", kor: "기괴한, 이상한" },
    { eng: "blanch", kor: "표백하다, 창백해지다" },
    { eng: "bland", kor: "온화한, 맛없는" },
    { eng: "blasphemy", kor: "신성모독" },
    { eng: "blatant", kor: "뻔뻔스러운, 노골적인" },
    { eng: "blemish", kor: "흠, 결점" },
    { eng: "blight", kor: "망치다, 병" },
    { eng: "bliss", kor: "더없는 행복" },
    { eng: "blithe", kor: "즐거운, 명랑한" },
    { eng: "blueprint", kor: "청사진, 계획" },
    { eng: "blunder", kor: "큰 실수, 실수하다" },
    { eng: "blunt", kor: "무딘, 퉁명스러운" },
    { eng: "blur", kor: "흐리게 하다, 흐림" },
    { eng: "blush", kor: "얼굴을 붉히다, 부끄러움" },
    { eng: "boisterous", kor: "떠들썩한, 활기찬" },
    { eng: "bolster", kor: "지지하다, 강화하다" },
    { eng: "bombastic", kor: "과장된, 허풍의" },
    { eng: "boon", kor: "은혜, 혜택" },
    { eng: "boorish", kor: "상스러운, 촌스러운" },
    { eng: "boost", kor: "밀어 올리다, 증진시키다" },
    { eng: "botch", kor: "망치다, 서투른 수선" },
    { eng: "bountiful", kor: "풍부한, 아낌없이 주는" },
    { eng: "boycott", kor: "불매운동하다" },
    { eng: "brace", kor: "대비하다, 버팀대" },
    { eng: "brandish", kor: "휘두르다" },
    { eng: "bravado", kor: "허세" },
    { eng: "brazen", kor: "뻔뻔한, 놋쇠로 만든" },
    { eng: "breach", kor: "위반, 위반하다" },
    { eng: "breakthrough", kor: "돌파구, 획기적인 발전" },
    { eng: "brevity", kor: "간결함" },
    { eng: "brisk", kor: "활발한, 상쾌한" },
    { eng: "brittle", kor: "부서지기 쉬운" },
    { eng: "broach", kor: "(이야기를) 꺼내다" },
    { eng: "browse", kor: "둘러보다, 검색하다" },
    { eng: "brunt", kor: "예봉, 주된 공격" },
    { eng: "brusque", kor: "무뚝뚝한, 퉁명스러운" },
    { eng: "bucolic", kor: "전원적인, 목가적인" },
    { eng: "bulky", kor: "부피가 큰" },
    { eng: "bully", kor: "괴롭히다, 약자를 괴롭히는 사람" },
    { eng: "bumptious", kor: "거만한, 잘난 체하는" },
    { eng: "buoyant", kor: "부력이 있는, 기운찬" },
    { eng: "burgeon", kor: "싹트다, 급성장하다" },
    { eng: "burnish", kor: "닦다, 광내다" },
    { eng: "buttress", kor: "지지하다, 버팀목" },
    { eng: "cabal", kor: "음모, 비밀 결사" },
    { eng: "cache", kor: "은닉처, 저장소" },
    { eng: "cacophony", kor: "불협화음" },
    { eng: "cajole", kor: "감언으로 꾀다" },
    { eng: "calamity", kor: "재앙, 재난" },
    { eng: "calculate", kor: "계산하다, 추정하다" },
    { eng: "caliber", kor: "구경, 능력" },
    { eng: "callous", kor: "무감각한, 냉담한" },
    { eng: "callow", kor: "미숙한, 풋내기의" },
    { eng: "calumny", kor: "비방, 중상" },
    { eng: "camaraderie", kor: "동지애, 우정" },
    { eng: "camouflage", kor: "위장, 위장하다" },
    { eng: "candid", kor: "솔직한, 공정한" },
    { eng: "candor", kor: "솔직, 정직" },
    { eng: "canine", kor: "개의, 송곳니" },
    { eng: "canny", kor: "약삭빠른, 영리한" },
    { eng: "cantankerous", kor: "성미가 고약한, 심술궂은" },
    { eng: "canvass", kor: "유세하다, 여론조사하다" },
    { eng: "capacious", kor: "널찍한, 넓은" },
    { eng: "capitulate", kor: "항복하다" },
    { eng: "capricious", kor: "변덕스러운" },
    { eng: "captivate", kor: "마음을 사로잡다, 매혹하다" },
    { eng: "carcinogen", kor: "발암 물질" },
    { eng: "cardinal", kor: "주요한, 기본적인" },
    { eng: "carnage", kor: "대학살" },
    { eng: "carnivorous", kor: "육식성의" },
    { eng: "castigate", kor: "혹평하다, 징계하다" },
    { eng: "casual", kor: "우연한, 격식을 차리지 않는" },
    { eng: "catalyst", kor: "촉매, 기폭제" },
    { eng: "catastrophe", kor: "대참사, 큰 재앙" },
    { eng: "categorical", kor: "단정적인, 절대적인" },
    { eng: "cater to", kor: "~의 요구에 응하다" },
    { eng: "catholic", kor: "보편적인, 폭넓은" },
    { eng: "caustic", kor: "부식성의, 신랄한" },
    { eng: "cavalier", kor: "무신경한, 거만한" },
    { eng: "cavil", kor: "트집을 잡다" },
    { eng: "cease", kor: "중단하다, 그만두다" },
    { eng: "cede", kor: "양도하다, 포기하다" },
    { eng: "celebrated", kor: "유명한" },
    { eng: "celerity", kor: "신속, 민첩" },
    { eng: "celestial", kor: "하늘의, 천체의" },
    { eng: "censor", kor: "검열하다, 검열관" },
    { eng: "censure", kor: "비난하다, 견책하다" },
    { eng: "census", kor: "인구 조사" },
    { eng: "cerebral", kor: "뇌의, 지적인" },
    { eng: "certify", kor: "증명하다, 보증하다" },
    { eng: "cessation", kor: "중단, 중지" },
    { eng: "chafe", kor: "쓸리게 하다, 짜증나게 하다" },
    { eng: "chagrin", kor: "분함, 원통함" },
    { eng: "champion", kor: "옹호하다, 지지하다" },
    { eng: "channel", kor: "경로, 수로, (자금을) 돌리다" },
    { eng: "chaotic", kor: "혼돈된, 무질서한" },
    { eng: "charismatic", kor: "카리스마 있는, 매력적인" },
    { eng: "charlatan", kor: "돌팔이, 사기꾼" },
    { eng: "chary", kor: "조심하는, 신중한" },
    { eng: "chasm", kor: "깊은 틈, 큰 차이" },
    { eng: "chaste", kor: "순결한, 정숙한" },
    { eng: "chastise", kor: "꾸짖다, 벌하다" },
    { eng: "chauvinism", kor: "맹목적 애국심" },
    { eng: "check", kor: "저지하다, 억제하다" },
    { eng: "cherish", kor: "소중히 여기다" },
    { eng: "chicanery", kor: "속임수, 책략" },
    { eng: "chide", kor: "꾸짖다" },
    { eng: "chimerical", kor: "비현실적인, 공상적인" },
    { eng: "choleric", kor: "화를 잘 내는" },
    { eng: "chronic", kor: "만성적인" },
    { eng: "chronological", kor: "연대순의" },
    { eng: "churlish", kor: "무례한, 막된" },
    { eng: "cipher", kor: "암호" },
    { eng: "circuitous", kor: "우회하는, 완곡한" },
    { eng: "circumlocution", kor: "에둘러 말하기, 완곡어법" },
    { eng: "circumnavigate", kor: "일주하다" },
    { eng: "circumscribe", kor: "제한하다, 선을 긋다" },
    { eng: "circumspect", kor: "신중한, 조심성 있는" },
    { eng: "circumvent", kor: "피하다, 우회하다" },
    { eng: "cite", kor: "인용하다, 언급하다" },
    { eng: "civil", kor: "시민의, 정중한" },
    { eng: "clairvoyant", kor: "천리안을 가진, 통찰력 있는" },
    { eng: "clamber", kor: "기어오르다" },
    { eng: "clamor", kor: "아우성, 소란" },
    { eng: "clandestine", kor: "비밀의, 은밀한" },
    { eng: "clarify", kor: "명확하게 하다" },
    { eng: "cleave", kor: "쪼개다, 고수하다" },
    { eng: "clemency", kor: "관용, 자비" },
    { eng: "cliche", kor: "진부한 표현" },
    { eng: "clientele", kor: "고객들, 의뢰인들" },
    { eng: "climactic", kor: "절정의, 최고조의" },
    { eng: "clinch", kor: "성사시키다, 결말을 내다" },
    { eng: "clique", kor: "파벌, 패거리" },
    { eng: "clog", kor: "막다, 막히다" },
    { eng: "cloister", kor: "수도원, 은둔 생활" },
    { eng: "clone", kor: "복제, 복제하다" },
    { eng: "clout", kor: "영향력, 힘" },
    { eng: "clown", kor: "광대, 어릿광대 짓을 하다" },
    { eng: "clumsy", kor: "서투른, 어색한" },
    { eng: "coagulate", kor: "응고하다, 굳어지다" },
    { eng: "coalesce", kor: "합치다, 연합하다" },
    { eng: "coerce", kor: "강요하다, 강제하다" },
    { eng: "cogent", kor: "설득력 있는" },
    { eng: "cogitate", kor: "숙고하다, 생각하다" },
    { eng: "cognate", kor: "조상이 같은, 동족의" },
    { eng: "cognitive", kor: "인식의, 인지의" },
    { eng: "cognizant", kor: "알고 있는, 인식하고 있는" },
    { eng: "coherent", kor: "일관성 있는, 논리적인" },
    { eng: "cohesive", kor: "결합력 있는, 응집성의" },
    { eng: "coincide", kor: "동시에 일어나다, 일치하다" },
    { eng: "collaborate", kor: "협력하다" },
    { eng: "collapse", kor: "붕괴되다, 무너지다" },
    { eng: "colleague", kor: "동료" },
    { eng: "collude", kor: "공모하다, 결탁하다" },
    { eng: "combat", kor: "전투, 싸우다" },
    { eng: "comely", kor: "아름다운, 어여쁜" },
    { eng: "comestible", kor: "먹을 수 있는, 식료품" },
    { eng: "comeuppance", kor: "당연한 벌" },
    { eng: "comfort", kor: "위로하다, 편안함" },
    { eng: "commandeer", kor: "징발하다, 강탈하다" },
    { eng: "commemorate", kor: "기념하다, 축하하다" },
    { eng: "commence", kor: "시작하다" },
    { eng: "commend", kor: "칭찬하다, 추천하다" },
    { eng: "commensurate", kor: "상응하는, 비례하는" },
    { eng: "commentary", kor: "논평, 해설" },
    { eng: "commiserate", kor: "동정하다, 불쌍히 여기다" },
    { eng: "commodious", kor: "넓은, 널찍한" },
    { eng: "commonplace", kor: "아주 흔한, 평범한" },
    { eng: "commotion", kor: "소동, 동요" },
    { eng: "communal", kor: "공동의, 공용의" },
    { eng: "compact", kor: "계약, 조밀한" },
    { eng: "compatible", kor: "양립할 수 있는, 호환되는" },
    { eng: "compelling", kor: "강력한, 설득력 있는" },
    { eng: "compensate", kor: "보상하다, 보충하다" },
    { eng: "competent", kor: "유능한, 자격이 있는" },
    { eng: "complacent", kor: "자기만족의, 안주하는" },
    { eng: "complain", kor: "불평하다" },
    { eng: "complaisant", kor: "공손한, 정중한" },
    { eng: "complement", kor: "보완하다, 보충물" },
    { eng: "compliant", kor: "순응하는, 고분고분한" },
    { eng: "complicity", kor: "공모, 연루" },
    { eng: "compliment", kor: "칭찬, 칭찬하다" },
    { eng: "comply", kor: "따르다, 준수하다" },
    { eng: "component", kor: "구성 요소, 부품" },
    { eng: "compose", kor: "구성하다, 작곡하다" },
    { eng: "compound", kor: "합성물, 악화시키다" },
    { eng: "comprehensive", kor: "포괄적인, 종합적인" },
    { eng: "compress", kor: "압축하다, 요약하다" },
    { eng: "comprise", kor: "포함하다, 구성되다" },
    { eng: "compromise", kor: "타협하다, 손상시키다" },
    { eng: "compunction", kor: "양심의 가책, 후회" },
    { eng: "compute", kor: "계산하다, 산출하다" },
    { eng: "concatenate", kor: "연결시키다, 사슬같이 잇다" },
    { eng: "concave", kor: "오목한" },
    { eng: "concede", kor: "인정하다, 양보하다" },
    { eng: "conceit", kor: "자만심, 자부심" },
    { eng: "conceive", kor: "상상하다, 임신하다" },
    { eng: "concentrate", kor: "집중하다, 농축하다" },
    { eng: "conception", kor: "개념, 임신" },
    { eng: "conciliatory", kor: "달래는, 회유적인" },
    { eng: "concise", kor: "간결한" },
    { eng: "conclave", kor: "비밀 회의" },
    { eng: "conclude", kor: "결론을 내리다, 끝내다" },
    { eng: "concoct", kor: "꾸며내다, 조작하다" },
    { eng: "concomitant", kor: "동시에 일어나는, 수반되는" },
    { eng: "concord", kor: "일치, 조화" },
    { eng: "concur", kor: "동의하다, 동시에 일어나다" },
    { eng: "condemn", kor: "비난하다, 선고를 내리다" },
    { eng: "condense", kor: "응축하다, 요약하다" },
    { eng: "condescend", kor: "자신을 낮추다, 거들먹거리다" },
    { eng: "condone", kor: "용서하다, 묵과하다" },
    { eng: "conducive", kor: "~에 좋은, 도움이 되는" },
    { eng: "conduct", kor: "행동하다, 지휘하다" },
    { eng: "confer", kor: "상의하다, 수여하다" },
    { eng: "confidant", kor: "절친한 친구" },
    { eng: "confine", kor: "제한하다, 가두다" },
    { eng: "confirm", kor: "확인하다, 승인하다" },
    { eng: "confiscate", kor: "몰수하다, 압수하다" },
    { eng: "conflagration", kor: "대화재" },
    { eng: "conflict", kor: "갈등, 충돌" },
    { eng: "conform", kor: "따르다, 순응하다" },
    { eng: "confound", kor: "혼동시키다, 당황하게 하다" },
    { eng: "confront", kor: "직면하다, 맞서다" },
    { eng: "confuse", kor: "혼란시키다, 혼동하다" },
    { eng: "congeal", kor: "응고시키다, 굳히다" },
    { eng: "congenial", kor: "마음이 맞는, 쾌적한" },
    { eng: "congenital", kor: "선천적인, 타고난" },
    { eng: "congest", kor: "혼잡하게 하다, 붐비게 하다" },
    { eng: "congregate", kor: "모이다, 집합하다" },
    { eng: "congruous", kor: "일치하는, 조화로운" },
    { eng: "conjecture", kor: "추측, 추측하다" },
    { eng: "connive", kor: "공모하다, 묵인하다" },
    { eng: "connoisseur", kor: "감정가, 전문가" },
    { eng: "conscientious", kor: "양심적인, 성실한" },
    { eng: "consecutive", kor: "연속적인" },
    { eng: "consensus", kor: "합의, 일치" },
    { eng: "conserve", kor: "보존하다, 보호하다" },
    { eng: "consign", kor: "위탁하다, 맡기다" },
    { eng: "console", kor: "위로하다" },
    { eng: "consolidate", kor: "통합하다, 강화하다" },
    { eng: "consonant", kor: "일치하는, 조화로운" },
    { eng: "consort", kor: "배우자, 어울리다" },
    { eng: "conspicuous", kor: "눈에 띄는, 현저한" },
    { eng: "conspire", kor: "공모하다, 음모를 꾸미다" },
    { eng: "constant", kor: "끊임없는, 불변의" },
    { eng: "constellation", kor: "별자리, 성운" },
    { eng: "consternation", kor: "경악, 대경실색" },
    { eng: "constituent", kor: "구성 요소, 유권자" },
    { eng: "constitute", kor: "구성하다, 제정하다" },
    { eng: "constrain", kor: "강요하다, 제한하다" },
    { eng: "constrict", kor: "죄다, 수축시키다" },
    { eng: "construe", kor: "해석하다, 추론하다" },
    { eng: "consummate", kor: "완성하다, 완벽한" },
    { eng: "contagious", kor: "전염성의" },
    { eng: "contain", kor: "포함하다, 억제하다" },
    { eng: "contaminate", kor: "오염시키다" }
];
